export const STORELOGINDATA = 'STORELOGINDATA';
export const REMOVEUSERDATA = 'REMOVEUSERDATA';
export const REMOVELOGOUTUSERID = 'REMOVELOGOUTUSERID';
export const STORELOGINID = 'STORELOGINID';
export const STOREUSERNAME = 'STOREUSERNAME';
export const STOREUSERWHOLEDATA = 'STOREUSERWHOLEDATA';
